### ISSUE TITLE
Tune swerve PID

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-Crescendo2024#23]
## Description
The swerve modules required additional PID tuning to prevent high levels of jerk when driving. 
Start with these from the previous year: https://github.com/FRC-1250/Team-1250-ChargedUp2023/blob/main/src/main/java/frc/robot/Constants.java#L148-L149

## Definition of done
- Tuned PID loop values have been merged to main

**Comment by Rodney-Lewis** [comment]
There was a change here that went untested prior to merging - https://github.com/FRC-1250/Team-1250-Crescendo2024/commit/5721621e49f21e72bff88ca99dce276a294dfa36

Openloop was changed to Velocity control for the drive wheels. The PID values may be too aggressive for however CTRE is configuring the motors.

**Comment by Icarus-21974** [comment]
Since we have already merged beta to main can I close this issue? Because the tuning felt fine during the time of testing. I just wanted to make sure before I close the issue.

**Comment by Rodney-Lewis** [comment]
We can mark this as completed for now. We're at the point where we need to really see it drive in an open field to do any better. I added open loop ramping to drive wheels in https://github.com/FRC-1250/Team-1250-Crescendo2024/commit/034faa33f4a5f828bbfc206ccd1f6bb340a2a0f4 which should also improve the situation a bit.
