### ISSUE TITLE
Tune shoulder PID

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-Crescendo2024#24]
## Description
The PID loop of the shoulder needs further tuning. As the gear ratio is high, P is likely the only variable required.

## Definition of done
- The PID loop of the shoulder is adequately responsive

**Comment by Icarus-21974** [comment]
is this finished since we somewhat tuned this tuesday? or do you feel there should be more done?

**Comment by Rodney-Lewis** [comment]
This issue is for fine tuning. We can likely make it go faster than it currently is.
