### ISSUE TITLE
Potential enhancement: Differential shooter wheel speeds

### ISSUE THREAD

**Issue by qwbmo** [FRC-1250/Team-1250-Crescendo2024#35]
Perhaps we should impart some spin to add angular momentum and flight stability.  There may also be some benefit to imparting spin based on which side of the speaker we're shooting from to promote the best reaction with the inside of the speaker side wall.

Low priority, obviously.

**Comment by Rodney-Lewis** [comment]
Handled physically on the robot by changing the gear ratio on one side of the shooter.

**Comment by Rodney-Lewis** [comment]
https://github.com/FRC-1250/Team-1250-Crescendo2024/commit/a7c8d76db40184592d8fb6b42a3835f9db0fc826
