### ISSUE TITLE
Shooter PID tuning

### ISSUE THREAD

**Issue by Icarus-21974** [FRC-1250/Team-1250-Crescendo2024#39]
The Pid wasn't up to our standards in the last meeting to my knowledge, is there any more tuning I should try while at home to test on Saturday? right now it is 2e-4 for both of the shooter wheels and to my memory that was only getting us about 4600 rpm

**Comment by Rodney-Lewis** [comment]
We were able to reach somewhere between 5050 - 5100 when asking for 5000. However, you can take another pass over this if you'd like. Since you can't test any adjustments with the robot, come up with a plan for how you're going to adjust the values prior.
