### ISSUE TITLE
Add system lights possible?

### ISSUE THREAD

**Issue by Icarus-21974** [FRC-1250/Team-1250-Crescendo2024#41]
I think it would be superbeneficial to add substation lights to the robot so that we can have a color code for different heights or if we have a note or not.

This idea is heavily suggested since we did break the bond on the robot because it seemed like the shoulder was not all the way home 

I also believe this will help with cycle time and prevent damage in the future

**Comment by Rodney-Lewis** [comment]
https://github.com/CrossTheRoadElec/Phoenix5-Examples/tree/master/Java%20General/CANdle

**Comment by Rodney-Lewis** [comment]
This how I'd try to do this... https://github.com/FRC-1250/Team-1250-Crescendo2024/commit/3808157180daf30afa56c5efedff40636de3e4aa
