### ISSUE TITLE
Create robot state machine

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-Crescendo2024#5]
## Description
The robot can exist in different states to do a task. Describe the states, their default actions, and what steps are required to transition from 1 state to another.

## Definition of done
- The following is outlined on this issue
  - Robot states
  - The default actions of these states
  - Which states can transition to what other states and what actions are required to do so

**Comment by Icarus-21974** [comment]
intaking mode = home = intake

amp mode 

subwoofer shot

3 pointer

climbing = amp 2 home
